In [1]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk import ngrams
import pandas as pd
import numpy as np

In [2]:
corpus = ['I love cats', 'Cats are cute', 'I like cats', 'Cats are cats', 'Cats watching cats', 'My life my rules']

In [3]:
# OHE
#pandas
voc_list = list(set(' '.join(corpus).lower().split()))
voc_list
ohe_df = pd.get_dummies(voc_list)
ohe_df['voc'] = voc_list
ohe_df.set_index('voc')

          are  cats  cute  i  life  like  love  my  rules  watching
voc
i           0     0     0  1     0     0     0   0      0         0
life        0     0     0  0     1     0     0   0      0         0
cats        0     1     0  0     0     0     0   0      0         0
rules       0     0     0  0     0     0     0   0      1         0
are         1     0     0  0     0     0     0   0      0         0
like        0     0     0  0     0     1     0   0      0         0
cute        0     0     1  0     0     0     0   0      0         0
my          0     0     0  0     0     0     0   1      0         0
watching    0     0     0  0     0     0     0   0      0         1
love        0     0     0  0     0     0     1   0      0         0

In [5]:
#Onehotenc
from sklearn.preprocessing import OneHotEncoder

vocabulary_array = np.array(voc_list).reshape(-1, 1)
ohe = OneHotEncoder()
ohe_data = ohe.fit_transform(vocabulary_array)
ohe_data.toarray()

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [10]:
ohe_df = pd.DataFrame(ohe_data.toarray(), columns=voc_list)
ohe_df['Vocabulary'] = voc_list
ohe_df = ohe_df.set_index('Vocabulary')
ohe_df

              i  life  cats  rules  are  like  cute   my  watching  love
Vocabulary
i           0.0   0.0   0.0    1.0  0.0   0.0   0.0  0.0       0.0   0.0
life        0.0   0.0   0.0    0.0  1.0   0.0   0.0  0.0       0.0   0.0
cats        0.0   1.0   0.0    0.0  0.0   0.0   0.0  0.0       0.0   0.0
rules       0.0   0.0   0.0    0.0  0.0   0.0   0.0  0.0       1.0   0.0
are         1.0   0.0   0.0    0.0  0.0   0.0   0.0  0.0       0.0   0.0
like        0.0   0.0   0.0    0.0  0.0   1.0   0.0  0.0       0.0   0.0
cute        0.0   0.0   1.0    0.0  0.0   0.0   0.0  0.0       0.0   0.0
my          0.0   0.0   0.0    0.0  0.0   0.0   0.0  1.0       0.0   0.0
watching    0.0   0.0   0.0    0.0  0.0   0.0   0.0  0.0       0.0   1.0
love        0.0   0.0   0.0    0.0  0.0   0.0   1.0  0.0       0.0   0.0

In [11]:
# BOW
cv = CountVectorizer(tokenizer= lambda text: text.split())
bow = cv.fit_transform(corpus)
cv.vocabulary_

{'i': 3,
 'love': 6,
 'cats': 1,
 'are': 0,
 'cute': 2,
 'like': 5,
 'watching': 9,
 'my': 7,
 'life': 4,
 'rules': 8}

In [12]:
# N-Grams
text = "The quick brown fox jumps over the lazy dog"
n_gram = ngrams(text.split(), 4)
for grams in n_gram:
  print(grams)

('The', 'quick', 'brown', 'fox')
('quick', 'brown', 'fox', 'jumps')
('brown', 'fox', 'jumps', 'over')
('fox', 'jumps', 'over', 'the')
('jumps', 'over', 'the', 'lazy')
('over', 'the', 'lazy', 'dog')

In [13]:
# TF IDF
tf = TfidfVectorizer()
output = tf.fit(corpus).transform(corpus)
tf.get_feature_names_out()
output.toarray()

array([[0.        , 0.45596865, 0.        , 0.        , 0.        ,
        0.88999584, 0.        , 0.        , 0.        ],
       [0.58951102, 0.36831339, 0.71890333, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.45596865, 0.        , 0.        , 0.88999584,
        0.        , 0.        , 0.        , 0.        ],
       [0.62483049, 0.78076043, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.7156639 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.69844483],
       [0.        , 0.        , 0.        , 0.40824829, 0.        ,
        0.        , 0.81649658, 0.40824829, 0.        ]])

In [14]:
df = pd.DataFrame(output.toarray(), columns=tf.get_feature_names_out())
df

,are,cats,cute,life,like,love,my,rules,watching
0,0.000000,0.455969,0.000000,0.000000,0.000000,0.889996,0.000000,0.000000,0.000000
1,0.589511,0.368313,0.718903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.455969,0.000000,0.000000,0.889996,0.000000,0.000000,0.000000,0.000000
3,0.624830,0.780760,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.715664,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.698445
5,0.000000,0.000000,0.000000,0.408248,0.000000,0.000000,0.816497,0.408248,0.000000